# -*- coding: utf-8 -*-
"""Machine Learning Klasifikasi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3lYYS6Q6JjZrusTiVsNMS2JuHqfcyv_

1. IMPORT LIBRARY
"""

import pandas as pd

"""2. LOAD DATASET"""

df = pd.read_excel('dataset machine learning.xlsx')
df.head()

"""4. FITUR/VARIABEL

"""

# Menampilkan nama kolom
print(df.columns)

# Info dataset
df.info()

"""5. STATISTIK DESKRIPTIF

"""

# Statistik deskriptif untuk data numerik
df.describe()

df.describe(include='all')

"""DATA PREPROSESING

1. CEK DATA KOSONG
"""

df.isnull().sum()

"""2. CEK DUPLIKASI"""

df.duplicated().sum()

print("Jumlah baris:", df.shape[0])
print("Jumlah kolom:", df.shape[1])

"""3. PISAHKAN FITUR DAN TARGET"""

X = df.drop('Nobeyesdad', axis=1)
y = df['Nobeyesdad']

"""4. HANDLING MISSING VALUES"""

# numerik → mean
for col in X.select_dtypes(include=['int64', 'float64']).columns:
    X[col].fillna(X[col].mean(), inplace=True)

# kategori → modus
for col in X.select_dtypes(include=['object']).columns:
    X[col].fillna(X[col].mode()[0], inplace=True)

"""5. ENCODING DATA KATEGORI"""

from sklearn.preprocessing import LabelEncoder

# Encode categorical features in X
for col in X.select_dtypes(include=['object']).columns:
    temp_le = LabelEncoder()
    X[col] = temp_le.fit_transform(X[col])

# Encode the target variable y. This 'le' will be stored later.
# Make sure this 'le' is available for the joblib.dump if intended.
le = LabelEncoder()
y = le.fit_transform(y)

"""6. MENANGANI OUTLIER"""

import numpy as np

for col in X.select_dtypes(include=['int64', 'float64']).columns:
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    X[col] = np.where(X[col] < lower, lower, X[col])
    X[col] = np.where(X[col] > upper, upper, X[col])

"""7. SCALLING"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

"""8. SPLIT DATA TRAINING DAN TESTING"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""9. HANDLE IMBALANCE"""

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

"""EKSPLORASI DATA

1. IMPORT LIBRARY VISUALISASI
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')

"""2. DISTRIBUSI FITUR NUMERIK"""

df.hist(figsize=(12,10))
plt.show()

"""3. DISTRIBUSI TARGET"""

sns.countplot(x='Nobeyesdad', data=df)
plt.title('Distribusi Kelas')
plt.xticks(rotation=45)
plt.show()

"""4. BOXPLOT"""

plt.figure(figsize=(12,6))
sns.boxplot(data=df)
plt.xticks(rotation=90)
plt.show()

"""5. HEATMAP KORELASI"""

plt.figure(figsize=(10,8))

# hanya numerik
corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""6. HUBUNGAN FITUR DENGAN TARGET"""

plt.figure(figsize=(8,6))
sns.boxplot(x='Nobeyesdad', y='Age', data=df)
plt.xticks(rotation=45)
plt.show()

"""DATA SPLITTING

1. VARIASI 1 → 80% : 20%
"""

from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""2. VARIASI 2 → 70% : 30%"""

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

"""3. VARIASI 3 → 90% : 10%"""

X_train3, X_test3, y_train3, y_test3 = train_test_split(
    X, y, test_size=0.1, random_state=42, stratify=y
)

"""4. CEK JUMLAH DATA"""

print("80:20 ->", X_train1.shape, X_test1.shape)
print("70:30 ->", X_train2.shape, X_test2.shape)
print("90:10 ->", X_train3.shape, X_test3.shape)

"""MODEL BUILDING

SMOTE
"""

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train1, y_train1 = smote.fit_resample(X_train1, y_train1)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

"""1. RANDOM FOREST"""

from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=25,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features='sqrt',
    random_state=42
)

model_rf.fit(X_train1, y_train1)
y_pred_rf = model_rf.predict(X_test1)

print("Random Forest:", accuracy_score(y_test1, y_pred_rf))
print(classification_report(y_test1, y_pred_rf))

"""2. XGBOOST"""

from xgboost import XGBClassifier

model_xgb = XGBClassifier(
    n_estimators=600,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='mlogloss'
)

model_xgb.fit(X_train1, y_train1)
y_pred_xgb = model_xgb.predict(X_test1)

print("XGBoost:", accuracy_score(y_test1, y_pred_xgb))
print(classification_report(y_test1, y_pred_xgb))

"""3. HIST GRADIENT BOOSTING"""

from sklearn.ensemble import HistGradientBoostingClassifier

model_hgb = HistGradientBoostingClassifier(
    max_iter=500,
    learning_rate=0.05,
    max_depth=10,
    random_state=42
)

model_hgb.fit(X_train1, y_train1)
y_pred_hgb = model_hgb.predict(X_test1)

print("Hist Gradient Boosting:", accuracy_score(y_test1, y_pred_hgb))
print(classification_report(y_test1, y_pred_hgb))

"""4. PERBANDINGAN AKURASI FINAL"""

results = {
    "Random Forest": accuracy_score(y_test1, y_pred_rf),
    "XGBoost": accuracy_score(y_test1, y_pred_xgb),
    "Hist Gradient Boosting": accuracy_score(y_test1, y_pred_hgb)
}

for model, acc in results.items():
    print(f"{model}: {acc:.4f}")

"""HYPERPARAMETER TUNING

1. TUNING RANDOM FOREST
"""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

param_rf = {
    'n_estimators': [300, 500],
    'max_depth': [20, 30, None],
    'min_samples_split': [2, 5],
}

grid_rf = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_rf,
    cv=3,
    n_jobs=-1
)

grid_rf.fit(X_train1, y_train1)

best_rf = grid_rf.best_estimator_

y_pred_rf = best_rf.predict(X_test1)

print("Best Random Forest:", accuracy_score(y_test1, y_pred_rf))
print("Best Params RF:", grid_rf.best_params_)

"""2. TUNING XGBOOST"""

from xgboost import XGBClassifier

param_xgb = {
    'n_estimators': [400, 600],
    'learning_rate': [0.03, 0.05],
    'max_depth': [4, 6, 8],
    'subsample': [0.8, 1.0]
}

grid_xgb = GridSearchCV(
    XGBClassifier(eval_metric='mlogloss', random_state=42),
    param_xgb,
    cv=3,
    n_jobs=-1
)

grid_xgb.fit(X_train1, y_train1)

best_xgb = grid_xgb.best_estimator_

y_pred_xgb = best_xgb.predict(X_test1)

print("Best XGBoost:", accuracy_score(y_test1, y_pred_xgb))
print("Best Params XGB:", grid_xgb.best_params_)

"""3. TUNING HIST GRADIENT BOOSTING"""

from sklearn.ensemble import HistGradientBoostingClassifier

param_hgb = {
    'max_iter': [300, 500],
    'learning_rate': [0.03, 0.05],
    'max_depth': [8, 10]
}

grid_hgb = GridSearchCV(
    HistGradientBoostingClassifier(random_state=42),
    param_hgb,
    cv=3,
    n_jobs=-1
)

grid_hgb.fit(X_train1, y_train1)

best_hgb = grid_hgb.best_estimator_

y_pred_hgb = best_hgb.predict(X_test1)

print("Best Hist GB:", accuracy_score(y_test1, y_pred_hgb))
print("Best Params HGB:", grid_hgb.best_params_)

"""4. PERBANDINGAN SETELAH TUNING"""

results = {
    "Random Forest": accuracy_score(y_test1, y_pred_rf),
    "XGBoost": accuracy_score(y_test1, y_pred_xgb),
    "Hist Gradient Boosting": accuracy_score(y_test1, y_pred_hgb)
}

for model, acc in results.items():
    print(f"{model}: {acc:.4f}")

"""MODEL EVALUATION

1. METRIK EVALUASI
"""

from sklearn.metrics import classification_report, confusion_matrix

print("=== Random Forest ===")
print(classification_report(y_test1, y_pred_rf))

print("=== XGBoost ===")
print(classification_report(y_test1, y_pred_xgb))

print("=== Hist Gradient Boosting ===")
print(classification_report(y_test1, y_pred_hgb))

"""2. CONFUSION MATRIX (MODEL TERBAIK)"""

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test1, y_pred_xgb)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix - XGBoost")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""3. PERBANDINGAN SEMUA MODEL"""

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

evaluation = pd.DataFrame({
    'Model': ['Random Forest', 'XGBoost', 'Hist Gradient Boosting'],
    'Accuracy': [
        accuracy_score(y_test1, y_pred_rf),
        accuracy_score(y_test1, y_pred_xgb),
        accuracy_score(y_test1, y_pred_hgb)
    ],
    'Precision': [
        precision_score(y_test1, y_pred_rf, average='weighted'),
        precision_score(y_test1, y_pred_xgb, average='weighted'),
        precision_score(y_test1, y_pred_hgb, average='weighted')
    ],
    'Recall': [
        recall_score(y_test1, y_pred_rf, average='weighted'),
        recall_score(y_test1, y_pred_xgb, average='weighted'),
        recall_score(y_test1, y_pred_hgb, average='weighted')
    ],
    'F1-Score': [
        f1_score(y_test1, y_pred_rf, average='weighted'),
        f1_score(y_test1, y_pred_xgb, average='weighted'),
        f1_score(y_test1, y_pred_hgb, average='weighted')
    ]
})

print(evaluation)

"""4. VISUALISASI PERBANDINGAN"""

import matplotlib.pyplot as plt

evaluation.set_index('Model')[['Accuracy', 'F1-Score']].plot(kind='bar')
plt.title("Perbandingan Model")
plt.ylabel("Score")
plt.xticks(rotation=30)
plt.show()

"""MODEL COMPARISON

1. TRAIN & SIMPAN HASIL SEMUA MODEL
"""

from sklearn.metrics import accuracy_score

results = []

# fungsi untuk training semua model
def evaluate_models(X_train, X_test, y_train, y_test, split_name):

    # Random Forest
    rf = RandomForestClassifier(n_estimators=500, max_depth=25, random_state=42)
    rf.fit(X_train, y_train)
    y_rf = rf.predict(X_test)

    # XGBoost
    xgb = XGBClassifier(n_estimators=500, learning_rate=0.03,
                        max_depth=6, random_state=42, eval_metric='mlogloss')
    xgb.fit(X_train, y_train)
    y_xgb = xgb.predict(X_test)

    # Hist Gradient Boosting
    hgb = HistGradientBoostingClassifier(max_iter=500, random_state=42)
    hgb.fit(X_train, y_train)
    y_hgb = hgb.predict(X_test)

    results.append([
        split_name,
        accuracy_score(y_test, y_rf),
        accuracy_score(y_test, y_xgb),
        accuracy_score(y_test, y_hgb)
    ])


# jalankan untuk semua split
evaluate_models(X_train1, X_test1, y_train1, y_test1, "80:20")
evaluate_models(X_train2, X_test2, y_train2, y_test2, "70:30")
evaluate_models(X_train3, X_test3, y_train3, y_test3, "90:10")

"""2. TABEL PERBANDINGAN"""

import pandas as pd

comparison_df = pd.DataFrame(results, columns=[
    'Split Data',
    'Random Forest',
    'XGBoost',
    'Hist Gradient Boosting'
])

print(comparison_df)

from sklearn.metrics import precision_score, recall_score, f1_score

def evaluate_metrics(model, X_test, y_test):
    y_pred = model.predict(X_test)
    return (
        accuracy_score(y_test, y_pred),
        precision_score(y_test, y_pred, average='weighted'),
        recall_score(y_test, y_pred, average='weighted'),
        f1_score(y_test, y_pred, average='weighted')
    )

"""3. VISUALISASI PERBANDINGAN"""

import matplotlib.pyplot as plt

comparison_df.set_index('Split Data').plot(kind='bar')
plt.title("Perbandingan Akurasi Model pada Berbagai Split Data")
plt.ylabel("Accuracy")
plt.xticks(rotation=0)
plt.show()

results = {
    "Random Forest": accuracy_score(y_test1, y_pred_rf),
    "XGBoost": accuracy_score(y_test1, y_pred_xgb),
    "Hist Gradient Boosting": accuracy_score(y_test1, y_pred_hgb)
}

best_model_name = max(results, key=results.get)
print("Model Terbaik:", best_model_name)

import joblib

# simpan nama kolom (SEBELUM scaling)
feature_names = df.drop('Nobeyesdad', axis=1).columns.tolist()

# ❗ BUAT ENCODER PER KOLOM (INI YANG KEMARIN KAMU BELUM SIMPAN)
from sklearn.preprocessing import LabelEncoder

encoders = {}
for col in df.select_dtypes(include=['object']).columns:
    le_temp = LabelEncoder()
    df[col] = le_temp.fit_transform(df[col])
    encoders[col] = le_temp

# simpan semua
joblib.dump({
    'model': best_hgb,
    'scaler': scaler,
    'label_encoder': le,
    'encoders': encoders,
    'feature_names': feature_names
}, 'model_obesitas.pkl')

"""UJI COBA DATA BARU

"""

import joblib
import pandas as pd

data = joblib.load('model_obesitas.pkl')

model = data['model']
scaler = data['scaler']
encoders = data['encoders']
le_target = data['label_encoder']
feature_names = data['feature_names']

data_baru = pd.DataFrame([{
    'Age': 20,
    'Gender': 'Female',
    'Height': 1.65,
    'Weight': 45,
    'FCVC': 3,
    'NCP': 2,
    'CH2O': 2,
    'FAF': 3,
    'TUE': 1,
    'family_history_with_overweight': 'no',
    'FAVC': 'no',
    'CAEC': 'Sometimes',
    'SMOKE': 'no',
    'SCC': 'yes',
    'CALC': 'no',
    'MTRANS': 'Walking'
}])

data_baru = data_baru.applymap(lambda x: x.strip() if isinstance(x, str) else x)

for col in data_baru.columns:
    if col in encoders:
        le = encoders[col]

        hasil = []
        for val in data_baru[col]:
            if val in le.classes_:
                hasil.append(le.transform([val])[0])
            else:
                print(f"⚠️ Value tidak dikenal di {col}: {val}")
                print("Kategori:", le.classes_)
                hasil.append(0)

        data_baru[col] = hasil

data_baru = data_baru[feature_names]

data_scaled = scaler.transform(data_baru)

hasil = model.predict(data_scaled)
hasil_label = le_target.inverse_transform(hasil)

print("Hasil Prediksi:", hasil_label[0])
